<html>
  <head>
    <title>Authorization</title>
    <link rel="stylesheet" href="./css/style.css">
  </head>
  <body>
    {% include 'header.phtml' %}
    <form action="http://localhost:8085/php2/lesson5/user/authorization/" method="post">
      <fieldset>
        <legend>Sign in</legend>
        <label>Login <input type="text" name="login" required></label>
        <label>Password <input type="password" name="password" required></label>
        <button type="submit"> Sign In </button>
      </fieldset>
    </form>
    {% include 'footer.phtml' %}
  </body>
</html>